### ISSUE TITLE
Rigify controller Rotated wrong side

### ISSUE THREAD

**Issue by ghost** [pKrime/Expy-Kit#1]
![Rig Hanc IK L R Rotated](https://user-images.githubusercontent.com/57253638/134930074-49aaae6b-49fa-447a-aa5b-3a8c914dd4c4.jpg)

![leg roteted After rigify](https://user-images.githubusercontent.com/57253638/134937792-f002ae8c-2d6d-41f3-9ef2-acd70b1c3dc2.jpg)

Hello 
This add-on is so good for faster and stress free rigging

using today 27 sep 6.30 zip file 
blender 2.93.4

Can You tell me how I can solve this issue 
1.hand Rigify IK controller Rotated wrong side
2. leg rotated after rigify generated

**Comment by pKrime** [comment]
Hi, depending on the rest pose and orient of the original bones, the script might not be able to determine the correct orient of the arm.

The quickest fix coming to my mind is to select the metarig, go in edit mode, select the arm, forearm and hand, Shift+N and pick "Global -Y Axis", then regenerate the rig. That should fix the bone orient

regards,
p.

**Comment by shubhampatilart** [comment]
Current Add-on progress Update I Download. solve all issues,

Your Add-on is save so much time
