### ISSUE TITLE
Cant get it to work in Blender 3.0

### ISSUE THREAD

**Issue by eArticleSolutions** [pKrime/Expy-Kit#10]
I downloaded the new version and cannot seem to bind the mesh after importing it back from Mixamo. Exporting is fine and it gets into Mixamo very well.

After downloading the fbx file from Mixamo. I select the two armatures like before, and then try to bind, and nothing happens.

Is it a bug or is there a new way of binding it?

I am using Blender 3.0 Stable version.

**Comment by pKrime** [comment]
Hi, are you by any chance selecting Rigify, rather than Rigify Controls, when binding a rigify full armature? Are there any constraints already on the controls that you are trying to bind? If you wish, you can delete all geometries and send me the .blend file

regards,
p.

**Comment by eArticleSolutions** [comment]
Wow. I guess I can chalk that up to mind exhaustion. I had been on a blender creation marathon and simply made a mistake. I have selected Rigify Controls and it is working perfectly.

Great job and thank you for this wonderful addon. I am a great fan.

**Comment by pKrime** [comment]
Thanks, I would love to watch your work when it's finished. There was no support for controls in the first release, and I named the deform skeleton just "Rigify". It will be "Rigify Deform" in next release

Cheers,
p.
