### ISSUE TITLE
Error with multiple roots in Unreal Engine when importing Rigify mesh after applying Game Friendly convertion

### ISSUE THREAD

**Issue by Anthony-MostlyHarmless** [pKrime/Expy-Kit#13]
Hi, 

So I created a Rigify armature in blender then assigned it to my mesh.

I then wanted to use your tool to make it Game Friendly in Unreal Engine. The addon tells me it renamed 10 bones, but when I export then import it in Unreal I get the following error:

    Multiple roots are found in the bone hierarchy. We only support single root bone. 

Have you encountered this problem before ?

Thanks for your help,

**Comment by pKrime** [comment]
Hi,

when exporting my characters I do the following:

1. Make Game Friendly (you did that)
2. Check "Deform Bones Only" in the .fbx options (you probably did that)
3. Make sure no other armatures are exported. Either by exporting only the selected objects, or removing the metarig and other armatures from the scene.

If you did that all of that already, chances are my addon doesn't support that rig type yet. Is it a human rig? Would you share the .blend? No geometries needed, the armature is enough

Cheers,
p.

**Comment by Anthony-MostlyHarmless** [comment]
Hi sorry for the delayed answer,

I'm dumb, N°2 : Check "Deform Bones Only" in the .fbx options (you probably did that) 

Did the trick :)

Thanks so much for your tool and help <3
