### ISSUE TITLE
I can't manage to apply Maximo animation on Rigify rig

### ISSUE THREAD

**Issue by tobiasBora** [pKrime/Expy-Kit#15]
First, thanks for this great package... Unfortunately, I can't make it work, as when I apply my animation, only a single point of my character seems to be parented to the mixamo's rig. Maybe I just did something stupid, I'm not sure.

**What I did**:

I have my meshed rigged using rigify. Then, I import Maximo's [backflip](https://www.mixamo.com/#/?page=1&query=backflip) animation, trying various options:

![image](https://user-images.githubusercontent.com/2164118/159953020-a997bbd5-15d8-4cde-842c-0a1d86ec6ada.png)

I remove then the character added by Maximo to keep only the rig:

![image](https://user-images.githubusercontent.com/2164118/159951092-164ba428-b6f2-41f4-9b87-562cd6ab7621.png)

Select the Rigify rig, then the Maximo rig using shift-click, then move to pose mode:

![image](https://user-images.githubusercontent.com/2164118/159953354-e143e7c7-9232-44d5-a026-2c85212655ea.png)

![image](https://user-images.githubusercontent.com/2164118/159953461-bb718b34-9d03-403c-ba5e-66bc488680fb.png)

Then, I do:

![image](https://user-images.githubusercontent.com/2164118/159953624-dd5b5c5f-aaac-4b9f-bb23-e63a85a7d4bd.png)

Then, my character has only a single point that seems to be animated, lets, arms... do not move:

![image](https://user-images.githubusercontent.com/2164118/159953937-3b2495f6-bdcf-4c00-8b54-a41b3d58d2e0.png)

Here is my blender file:

[a.zip](https://github.com/pKrime/Expy-Kit/files/8343097/a.zip)

**Comment by pKrime** [comment]
Hi, I have found the following issues:

- the rig has constraints already
- the animated armature is a metarig, not mixamo
- the rig somehow broke

You can regenerate the rig or download the fix from here

[a.zip](https://github.com/pKrime/Expy-Kit/files/8344122/a.zip)

then in your settings you should use

To Bind: Rigify Controls
Bind Target: Rigify Metarig

This way I can see your character doing the jump

https://user-images.githubusercontent.com/5176115/159979419-c633c7be-8a1a-4429-a971-4441c4e0de13.mov

**Comment by tobiasBora** [comment]
Ohaou that's really cool, thank you so much! I should try again, but I'm not sure I understand the exact procedure to follow : do you suggest that I should recreate the rig or also the metarig from scratch?

I'm also not sure to understand, what do you mean by ''the animated armature is a metarig, not mixamo"? I did imported the animation from a fbx file. You mean I imported it poorly?

Also, why in your third comment there is no reference at all to Mixamo ? I guess that somehow mixamo's skeleton should be involved no?

**Comment by pKrime** [comment]
Hi

_>>do you suggest that I should recreate the rig or also the metarig from scratch?_

you don't need to: just select the metarig from the Bob collection and hit Re-Generate Rig in the Armature properties

![immagine](https://user-images.githubusercontent.com/5176115/160208311-1c3cd7dc-c1f0-40c3-9e68-25cc5653899b.png)

_>>what do you mean by ''the animated armature is a metarig, not mixamo"? I did imported the animation from a fbx file. You mean I imported it poorly?_

I'm not sure why, but the Armature that moves is called "metarig.001" and the bones follow the metarig configuration (spine.00x, upper_arm.L), not Mixamo. Perhaps "Convert Bone Names" has been used involuntarily.

![immagine](https://user-images.githubusercontent.com/5176115/160208325-55cb82fb-8f1d-4e38-9d0c-945b31001aad.png)

It's completely fine, but you will have to use these settings

![immagine](https://user-images.githubusercontent.com/5176115/160208285-99adc026-4a4e-4d81-9929-ba0cb3e52922.png)

**Comment by tobiasBora** [comment]
Hi, sorry for my late answer: I never had the time to test it again before today, but I confirm this works like a charm. Thank you so much for this great tool!

**Comment by tobiasBora** [comment]
PS: it would be great to have a few lines in the doc explaining how to debug this, notably when to choose metarig, when to choose mixamo etc… explaining how these format differ and how to recognize a given format.

**Comment by pKrime** [comment]
Hi, thanks for the update: I'm glad you sorted it out. The main reason why there are no docs yet is that Expy Kit has changed a lot based on the user feedback. Most changes are done though, perhaps the time is right!
