### ISSUE TITLE
After renaming "Mixamo to UE" model with multiple NLA actions, animations not playing

### ISSUE THREAD

**Issue by larinius** [pKrime/Expy-Kit#16]
Model is rigged and animated With Mixamo. Multiple animations combined with NLA editor.
This file successfully exported as GLB into Godot Engine - actions exported as animations.

Tried to use add-on to export model for Unreal Engine, but have and issue:
Rename bones from Mixamo to UE and save as FBX - model has list of animation tracks but not playing. Model freeze in current static pose.

How to fix it? 

In attached files, my Blend file and result fbx.

**Blender version: 3.0.1**

[SWGirl_2.zip](https://github.com/pKrime/Expy-Kit/files/8348997/SWGirl_2.zip)
[Output FBX SWGirl_2.zip](https://github.com/pKrime/Expy-Kit/files/8349030/Output.FBX.SWGirl_2.zip)

**Comment by larinius** [comment]
Also I checked animations into Blender they also not work after renaming.

**Comment by pKrime** [comment]
It's fixed bro, please update! :)
