### ISSUE TITLE
Add preset for Character Creator(CC3) Model

### ISSUE THREAD

**Issue by butaixianran** [pKrime/Expy-Kit#19]
A good part about this project is it comes with some very useful build-in preset, like Daz and mixamo.

But these 2-3 yesars, iclone's Character Creator(CC) is killing Daz. 

A lot of game studios are adding CC to their workflow. So, support CC is supporting the future.

In that case, would you like to add CC's bone mapping as a build-in preset?

**Comment by pKrime** [comment]
Hi! This is just to let you know that I am not ignoring this request, but CC's installer keeps crashing and I don't know how to fix it!
Do Actore Core characters follow the Character Creator convention? That would make it easier

Cheers,
p.

**Comment by butaixianran** [comment]
Actore Core characters use the same bone name and bone structure as CC3 character. 

But it can not be imported by Blender CC addon, may be something wrong when handling materials. So you have to import it as fbx.
