### ISSUE TITLE
Problem with new Rigify face rig in Blender 3.1+ and Rigify Game Friendly

### ISSUE THREAD

**Issue by 0Auslander0** [pKrime/Expy-Kit#20]
When applying the Rigify Game Friendly feature to a Rigify rig with an updated face rig and then exporting the rig to Unreal Engine, an import error occurs.

![fbxError](https://user-images.githubusercontent.com/105365628/167868748-bbf53f34-07d4-44c0-8e7c-09c242dbed19.png)

The problem manifested itself after upgrading the old Rigify face rig from Blender 2.9 to the new version 3.1+ using the Upgrade Face Rig feature in Metarig. If you do not update the facial rig, everything works correctly.

![metarigUpgrade](https://user-images.githubusercontent.com/105365628/167869793-e3309ad6-d6ad-498b-ba1d-357a9bc6a3bf.png)

 I compared the fbx files of the correct rig and the rig with the problem and found that the problem rig contains unnecessary bones that are not deformation bones which are defined as the second root bone in UnrealEngine. The additional bones in the images below are initially located in the same place as the rig itself, I moved them to the side so that they can be seen.

![BadrigFront](https://user-images.githubusercontent.com/105365628/167873739-1f12dfac-39b6-4bfc-989a-3fffb937696d.png)
![BadrigRight](https://user-images.githubusercontent.com/105365628/167873767-1d242239-0f77-4975-be74-428f9df8c6c2.png)
![Bones](https://user-images.githubusercontent.com/105365628/167873795-bfcce86d-0695-4b8d-a180-9f8bcdedbab8.png)

At the beginning, I thought that the problem was related to the chest physics bones, which are necessary for the Spring bones addon to work, but after removing them completely, nothing has changed.

I will be grateful if you solve this problem. And thank you for a wonderful tool.

**Comment by pKrime** [comment]
Hi, I can confirm the issue, thanks for pointing this out. I think that the problem are the bones of the eyes, I'll work on a fix

cheers,
p.

**Comment by 0Auslander0** [comment]
Thank you for your reply. I will wait for news. Good luck to you.

**Comment by pKrime** [comment]
Hi, this should be fixed with 6938e7e8610f9e172fe59f1974c7757fe5e04073

If confirmed working I will make new packages

Cheers!

**Comment by 0Auslander0** [comment]
Hello. I checked and everything seems to be working. I also looked at the hierarchy of bones and with it, everything seems to be in order, both in Blender and Unreal Engine, there were no errors. Anyway, if I find anything I'll let you know. Thank you for your hard work.
