### ISSUE TITLE
Arms are twisted at third import

### ISSUE THREAD

**Issue by j2l** [pKrime/Expy-Kit#21]
I successfully imported FBX animation from mixamo and applied to rig and baked.
But then, the third FBX from mixamo (same character, no skin), I've got arms inverted (not legs):
![image](https://user-images.githubusercontent.com/65325/172826704-ce1f55f4-2e3c-4e5b-b97f-3a8440a2c2ec.png)

Did it happen to you?
Any idea?

**Comment by pKrime** [comment]
Hi, please try "Match Bone Orient" in the Match Transform setting, and hope for the best!

**Comment by j2l** [comment]
Thank you very much @pKrime!
Wonderful add-on, congrats!

Unfortunately, setting bone transform deforms fingers badly.

Should I look to bone constraints to check for issue?
Is it a rotation or location issue?

Would LOVE some documentation :smile_cat:

**Comment by pKrime** [comment]
Hi,

please send me a .blend file containing the armature if possible, I'll see if that can be fixed in the script

>Would LOVE some documentation

I think it would be about time, but due to time constraints I'm afraid that's not happening anytime soon, we'll see!

p.

**Comment by j2l** [comment]
Thank you,
Here's the blend with the default makehuman example.
If you bind without bone transform, it's crossed. If you add bone transform it's OK but fingers are deformed.
[untitled.blend.zip](https://github.com/pKrime/Expy-Kit/files/8871046/untitled.blend.zip)

**Comment by j2l** [comment]
Just stumbled on [this](https://youtu.be/XoASUhJ7OGM?t=67) 
So it might be related to the NLA blending mode

**Comment by pKrime** [comment]
Hi, I can see that Expy Kit doesn't work well with this character's fingers, I'll try to understand what is wrong

**Comment by j2l** [comment]
maybe this help for fingers https://youtu.be/UpAxY519IJU?t=326 ?

**Comment by pKrime** [comment]
I will look at that, thank you! Those fingers are stopping me from releasing a bugfix version

**Comment by j2l** [comment]
Glad I can help.
I'm crossing fingers (not like the armature 😄 ), hoping you'll find out!

**Comment by jjp9624022** [comment]
oh please release the bugfix version, maybe the new rigify cause the bug

**Comment by pKrime** [comment]
Hi, I still should fix this the right way, anyway, there was a bug in the **No Finger Location** option that prevent it from working. Now that it's fixed (992867dc81fde6e3484d5497e88b2b1e4f245eef), this issue is mitigated

Cheers,
p.

**Comment by j2l** [comment]
great, thanks!

**Comment by kadattack** [comment]
I have the same issue with the current version. 
![Screenshot from 2022-09-26 19-14-12](https://user-images.githubusercontent.com/78758877/192340254-4c30ec50-cc16-48f7-8dd1-558720545ddf.png)

I've added my blend file saved right before mapping it with the plugin
[blend file](https://mega.nz/file/DAxCkT5b#p4uNijqj4M4ktfqmGqngomKe_zcMbP3SavoqHp0uxtY)

**Comment by pKrime** [comment]
> I have the same issue with the current version

Hi, thanks for the .blend file, it will be very useful. I wrote the Matching function with a very narrow scope in mind, it should be rethought entirely so it is taking time for fixing it, but the more examples I have, the better I can make my mind about it.

Cheers!

**Comment by kadattack** [comment]
Thank you. Yes I downloaded a random animation without skin from mixamo and tried to bind it. I guess i will try to do it manually for now.

**Comment by kiskit** [comment]
I'm joining in to report the same issue with 0.5.2. With a fresh rig from Rigify, arms position is all wrong in all fbx I downloaded from Mixamo. That said, I watched a couple of tutorials and they all talk about downloading uploading the mesh, applying an animation, then downloading that animation and finally retargeting in Blender. I just have a rigify rig, nothing that went through the mixamo windmill. Does that mean that my rig needs to be in T pose for the retargeting to work properly?

**Comment by pKrime** [comment]
Hi Kiskit,

At present, Expy Kit is more of an export tool than a retargeting one. I wrote it to export my characters to Unreal Engine and Mixamo, and to use Rigify on Unreal Engine characters.

The only conversion it supports at the moment, is binding a non T-pose character to a T-pose armature using the "Match Bone Transform" option, but so far it only covers the Mixamo "without skin" armature.

I have written a more universal solution that supposedly works on paper, but didn't have time to implement it yet. In theory, retargeting between different rigs is already possible by tweaking the additional bones that are secretly added to the target armature. I have never displayed that because I want to change the way it works, and non valid workflows potentially showing around would end up being confusing.

Stick around for the new system (but I doubt it will be out this year), and let me know if you have any suggestion

Cheers,
p.

**Comment by pKrime** [comment]
Hi, version 0.6 supports can use the current pose for binding and solves this issue. Please re-open if still not working, cheers!
