### ISSUE TITLE
Binding Rigify_Controls to Mixamo Rig blows up my Rigify Rig

### ISSUE THREAD

**Issue by martenzander** [pKrime/Expy-Kit#27]
Hey, I juzst created a rigify rig based on a mixamo rig. I did everything like it was explained in the video tutorial. First I extracted a Metarig and then re-generated a rigify rig. When trying to bind my new rigify rig to a mixamo animation now, this is what my rigify controls look like:

![image](https://user-images.githubusercontent.com/8024997/210363660-249bd6f0-493e-4c35-8399-5d814b03c6ba.png)

Any idea what is going on? I am using Blender 3.3.1

**Comment by martenzander** [comment]
oh and here is a link to the blend file in case you would like to investigate :)
https://drive.google.com/file/d/1H8fSGBOYqt45KleYnSiEi08BULXcEmfE/view?usp=share_link

**Comment by pKrime** [comment]
Hi, thanks for the sending the .blend file. At the moment the only Matching option that seems to work for this case is the experimental Match Armature Pose, which requires aligning the two characters first and is still alpha.

I see that the metarig rest pose differs from the animated Armature, does it come from a different Mixamo character?

regards,
p.

**Comment by martenzander** [comment]
Hey there, thanks for the quick response!
Actually the animated armature should come from the exact same mixamo character. I was using mixamo's swat guy as you might already know after looking into the blend file. However, when downloading the character for the first time, I was using the option "t-pose". Maybe I should have kept the original pose for the purpose of retargeting, because when downloading animations you don't have that option anymore and probably all animated skeletons have their original bind/rest pose.

**Comment by lzychowski** [comment]
> at the moment the only Matching option that seems to work for this case is the experimental Match Armature Pose

can confirm that using this option fixed my issue

**Comment by pKrime** [comment]
In version 0.6 Match Armature Pose was renamed as "Current Pose is Target Rest Pose". Please re-open if there are still issues

p.
