### ISSUE TITLE
After opening this plugin, the operation will become stuttering

### ISSUE THREAD

**Issue by iillya** [pKrime/Expy-Kit#29]
After opening this plugin, the operation like raising feet in pose mode will become stuttering.Closed is noticeably smoother

**Comment by pKrime** [comment]
Hi, at the moment there is more than one version of Expy Kit around. Just to make sure, did you use one of the packaged main version, or did you try the experimental Mesh Widgets branch? The latter is more likely to cause such behaviour, even if it's the first time I hear something like that happening.

**Comment by iillya** [comment]
blender 3.3.4
Expy 0.5.2
<img width="1325" alt="Snipaste_2023-03-01_19-01-00" src="https://user-images.githubusercontent.com/112866800/222122210-f2158de8-ac55-4bf7-935c-fe168f68e9ea.png">

blender file was clean，only the Armature

**Comment by iillya** [comment]
[rig.zip](https://github.com/pKrime/Expy-Kit/files/10860222/rig.zip)
The blender file I use

**Comment by iillya** [comment]
> Hi, at the moment there is more than one version of Expy Kit around. Just to make sure, did you use one of the packaged main version, or did you try the experimental Mesh Widgets branch? The latter is more likely to cause such behaviour, even if it's the first time I hear something like that happening.

The frame rate is only 6,but closing the addon it becomes normal

**Comment by pKrime** [comment]
Hi, I will check the poll methods, perhaps there are some in the interface. Does it halp if you close the viewport properties by pressing N?

**Comment by iillya** [comment]
> Hi, I will check the poll methods, perhaps there are some in the interface. Does it halp if you close the viewport properties by pressing N?

Hi.Yes, this method works,but why

**Comment by pKrime** [comment]
Hi, there is probably some check going on in my UI class, I'll check where it is. Also, perhaps just collapsing the fingers should improve the performance.

Glad we could pinpoint that and find a temporary solution, please hold on until it's fixed!

Cheers,
p.

**Comment by pKrime** [comment]
Hi, I did finally manage to reproduce this. It looks more like a blender bug than an Expy Kit's fault, but I think that I have found a workaround.

**Comment by iillya** [comment]
> Hi, I did finally manage to reproduce this. It looks more like a blender bug than an Expy Kit's fault, but I think that I have found a workaround.

It's okay, you've done a great job.

**Comment by pKrime** [comment]
Thanks @iillya. This issue has been at least mitigated by my rewrite and blender 4.0 optimization. Please re-open if it becomes a problem again!
