### ISSUE TITLE
inactive settings

### ISSUE THREAD

**Issue by dallhuzur** [pKrime/Expy-Kit#32]
Hello
The problem is that no matter what functions are used, the settings window is inactive and an attempt to select presets writes "none". At the same time, retargeting works (but finger problem, yeah), but I can’t set it up in any way, because the window is inactive. What could be the problem?
Thanks in advance for your reply
![image](https://github.com/pKrime/Expy-Kit/assets/133299545/f3082046-0517-4ed1-9c54-642514c97503)
![image](https://github.com/pKrime/Expy-Kit/assets/133299545/8b350b23-a124-4278-a51c-9acb35f00406)

**Comment by pKrime** [comment]
Hi, does it happens with all rigs? We have to rule out any install problem, have you tried to remove and reinstall the add-on? Lastly, would you please send a .blend file with just the Armatures, no geometry? I will try to reproduce the error.

**Comment by pKrime** [comment]
Hi,

any chance **Global Undo** is disabled or **Undo Steps** are set to **0** in **Edit** -> **Preferences** -> **System**? Blender operators rely on the undo system to set parameters (internally, changing a parameter undoes the operation and runs it again)

![immagine](https://github.com/pKrime/Expy-Kit/assets/5176115/dbeaf37a-44b0-45b8-be14-a56993a6297d)

Your character and the mocap have a different proportion and rest pose, and expy kit wasn't initially designed for that, but I get good results if I put your character in T-pose manually and set Transform Matching to Match Armature Pose. This operation will be automated in the next release.

Cheers!

**Comment by dallhuzur** [comment]
Oh yes, Global undo turned out to be a problem, now everything works 👍
Aaand oh, my bad, I think I sent the rig without optimization sorry, but there were no problems with the pose, the grip of the hands was still not needed, so the problem was more with the legs, but now everything is fine, thanks
