### ISSUE TITLE
Without rigging 

### ISSUE THREAD

**Issue by elkhalafy** [pKrime/Expy-Kit#35]
Hi pKrime.

Can you implement this paper inside blender as free add-on??

The paper or idea for character animation without rigging based on Pixar's paper called character articulation through profile curves, so if you able implement it inside blender 2.93 and higher, it will be amazing and faster Way than old fashioned way that needs bones, weight painting etc..

Watch the video and download the paper too

https://youtu.be/gUJ4RxMdVn8

Download the paper here :-

https://graphics.pixar.com/library/ProfileMover/paper.pdf

Thank you.

**Comment by pKrime** [comment]
Hi!

That paper is definetely on my radar but it's kind of the final boss of character development, some level-up is required! :)

Besides, I am not sure that can be done entirely in the form of an add-on: it probably requires some involvement from the blender dev team

But thanks for enquiring about that, let's see what the future holds! :)

**Comment by elkhalafy** [comment]
Thank you, 

But I'm sure you can done it entirely as add-on. I'm sure, but try, I hope implement it, you will save us 

Blender dev team, they added it on their roadmap but in the future not now, so the addon is solution right now, if you created it, please support it from  blender 2.93 and higher.

Thank you.

**Comment by elkhalafy** [comment]
Your personal email please

**Comment by elkhalafy** [comment]
Anyway, any news yet
