### ISSUE TITLE
Tutorials on use or documentation anywhere?

### ISSUE THREAD

**Issue by lukefreeze** [pKrime/Expy-Kit#36]
Hello, I think this tool is great and I have used it to extract a meta rig and rebuild rigify rig to control my UE4 mannequin. However I have no idea how to get this animated rig out of blender and into unreal engine on to the original mannequin. Any advice guidance or tutorial you can recommend would be much appreciated as I am losing my mind trying to find any answers. 

Currently when I export the rig I get the error from unreal of extra joints that were not in the original skeleton. I then tried convert bone names to rename deform bones to unreal but still have the same issue where it is exporting everything. If you could help me figure out what to do here I will be showing lots of other people this tool as this is exactly what people learning games dev for unreal want so they can bring their own animations in to unreal engine.

**Comment by lukefreeze** [comment]
The following bones exist in the imported animation, but not in the Skeleton asset SK_Mannequin_Skeleton.  Any animation on these bones will not be imported: 

 DEF-spine_005  
head_001  
clavicle_l_001  
DEF-palm_01_L  
index_01_l_001  
index_02_l_001  
index_03_l_001  
thumb_01_l_001  
thumb_02_l_001  
thumb_03_l_001  
DEF-palm_02_L  
middle_01_l_001  
middle_02_l_001  
middle_03_l_001  
DEF-palm_03_L  
ring_01_l_001  
ring_02_l_001  
ring_03_l_001  
DEF-palm_04_L  
pinky_01_l_001  
pinky_02_l_001  
pinky_03_l_001  
clavicle_r_001  
DEF-palm_01_R  
index_01_r_001  
index_02_r_001  
index_03_r_001  
thumb_01_r_001  
thumb_02_r_001  
thumb_03_r_001  
DEF-palm_02_R  
middle_01_r_001  
middle_02_r_001  
middle_03_r_001  
DEF-palm_03_R  
ring_01_r_001  
ring_02_r_001  
ring_03_r_001  
DEF-palm_04_R  
pinky_01_r_001  
pinky_02_r_001  
pinky_03_r_001  
DEF-breast_L  
DEF-breast_R  
DEF-pelvis_L  
DEF-pelvis_R

**Comment by pKrime** [comment]
Hi, I usually import the Unreal Engine .fbx in blender again, bind it to an animated rigify armature with Expy Kit, bake the animations and export the animated Unreal Engine .fbx Armature. That worked way better than renaming Rigify to Unreal, which would not work anyway since DEF-head is renamed head.001, to avoid clashing with the "head" control bone.

Sorry if that's a bit unclear, and I agree that a manual would be a great addition. Please let me know if you need help with our animations.

**Comment by lukefreeze** [comment]
found the answer in this tutorial:
https://www.youtube.com/watch?v=qRmGyX64KcA&ab_channel=PixelicaCG

**Comment by pKrime** [comment]
Hi, I didn't know of that channel, thanks a lot! I am getting many DMs on how to integrate Unreal, so it's time for a few new videos. I am closing this issue in the meantime, please let me know if you need help

cheers!
p.

**Comment by lukefreeze** [comment]
So I managed to get the animation on to the unnreal mannequin using bind active however this only works when the unreal mannequin has been imported with automatic orienting and force connect children options checked on. The problem with this is that when you try to import this animation in to unreal you get a series of errors saying you root bone has no animation track and when you get around this all animation is screwed up as the bone orientations are wrong. 

Is it possible to get this workflow to work? Has anyone brought the unreal mannequin in to blender, used expy to extract metarig and build rigify rig then reapply the animation to the unreal engine rig and bring it back in to unreal engine to apply to the unreal mannequin? And if so do they have a recording of them doing this/any documentation?

**Comment by pKrime** [comment]
Hi,
I do that for my Unreal projects, I have no video of the full process at
the moment, but you can check my very first video of Expy Kit, in which I
import the Unreal mannequin without auto orientation, apply an animation
and export it to Unreal Engine.

https://www.youtube.com/watch?v=pFouaNVxcso

The difference here is that you will have to bind the Unreal Mannequin
(with its original orientation) to a Rigify rig using Expy Kit, bake the
animation(s) and export them to .fbx.

If it's urgent, please jump on the discord server and we will try to make
it work.

https://discord.com/invite/HcRyVvfFBD

Cheers,
p.

Paolo Acampora, ***@***.***
M +39 392 5661998
uk.linkedin.com/in/paoloac

**Comment by lukefreeze** [comment]
Thank you so much for the quick response. I will jump on the discord

**Comment by lukefreeze** [comment]
I figured it out now. I need to set the unreal mannequin in the to bind option and I need to turn off copy IK roll. This then makesit work
