### ISSUE TITLE
only bakes the first keyframe and doesnt remove the the constraints 

### ISSUE THREAD

**Issue by Ulf3000** [pKrime/Expy-Kit#38]
your baking function (menuitem3->menuitem2) doesnt bake the animation. it stops after the first frame (it creates 2 keyframes , one on frame 0 and one on frame 1 )

**Comment by pKrime** [comment]
Hi, I couldn't reproduce that, but I have seen something similar happening: that function bakes all the animations in the scene. If there is a 2 keyframes animation for that armature it's going to be baked and, if processed last, applied. Any chance you will find the animation you were looking for in the Action Editor?

Please, send a .blend file with the two armatures if that keeps happening!
