### ISSUE TITLE
Bind to active armature is broken on Blender 4.0

### ISSUE THREAD

**Issue by Fmk89** [pKrime/Expy-Kit#39]
Expy-Kit-main\operators.py", line 1206, in invoke
    return self.execute(context)
Expy-Kit-main\operators.py", line 1466, in execute
    new_bone.layers[self.ret_bones_layer] = True
AttributeError: 'EditBone' object has no attribute 'layers'

**Comment by pKrime** [comment]
Hi!

I have fixed that in the development version, you can download it from the big green button. Expy Kit 0.6 is imminent, I just can't find the time to  release it. Please let me know if there are troubles in downloading the code.

**Comment by Fmk89** [comment]
Thank you! 👍

**Comment by MikeX7** [comment]
i have the same issue (since blender 4 changed the bone layer setup), and i downloaded the latest version directly from the git.

**Comment by pKrime** [comment]
Hi, it is fixed in version 0.6, which is not released on github. Please, use either the big green "Code" button to download or clone the repo, or go to the Gumroad page to get a .zip

https://ballsandninjas.gumroad.com/l/xotibs

**Comment by MikeX7** [comment]
> Hi, it is fixed in version 0.6, which is not released on github. Please, use either the big green "Code" button to download or clone the repo, or go to the Gumroad page to get a .zip
> 
> https://ballsandninjas.gumroad.com/l/xotibs

I am using the version 0.6 
![image](https://github.com/pKrime/Expy-Kit/assets/5867974/ff65526e-1bde-4671-852c-be27a0659379)
 
It's the latest version here directly from the repo. I can also try the one on gumroad to see if it makes any difference.

**Comment by schroef** [comment]
> Hi!
> 
> I have fixed that in the development version, you can download it from the big green button. Expy Kit 0.6 is imminent, I just can't find the time to release it. Please let me know if there are troubles in downloading the code.

Could you be more clear, there is no 'big green' button no more. Perhaps a more and better descriptive message helps.
Ive tried that "extra_features" branch, since i noticed the version bump tp v0.6.1 But that still has layers in the script

![Screenshot 2024-10-03 124857](https://github.com/user-attachments/assets/e4d9dfc6-e5d8-4fd7-bf4a-630b7a0d7abb)
![Screenshot 2024-10-03 124918](https://github.com/user-attachments/assets/5d50ac9c-52b5-4d50-a26b-da4610cd9efe)
