### ISSUE TITLE
Presets broken after installig the AddOn on 4.1 & 4.2

### ISSUE THREAD

**Issue by AugustoPapagno** [pKrime/Expy-Kit#54]
Hi, after quite a bit of troubleshooting,I did found that this add on is breaking the presets selection on Blender, starting in 4.1 (Issue https://projects.blender.org/blender/blender/issues/125508#issuecomment-1259299)
Please do fix it.

Best regards,

Augusto Papagno

**Comment by pKrime** [comment]
Hi, I have reproduced the issue and pushed a quick fix (d96e0e1). I'm not even sure it's an Expy Kit issue, as it happens with other addons as well: deriving a class from blender's startup scripts somehow compromises the usage of the base class.

Thanks for reporting this: I would have hardly noticed this!
