### ISSUE TITLE
Issues with latest blender releases

### ISSUE THREAD

**Issue by eArticleSolutions** [pKrime/Expy-Kit#7]
It does not work on 2.93.5 and 3.0 alpha or beta

**Comment by pKrime** [comment]
Hi, can you be more specific: I'm using it on blender 3.0.0 alpha, will try the beta ASAP.

**Comment by eArticleSolutions** [comment]
When I try to right-click, nothing happens. All bones in pose mode are deselected and the pose context menu does not show. It works well with 2.92.

**Comment by pKrime** [comment]
Hi, that looks like "Right Click Selection": if no menu shows at all, it's hardly Expy-Kit's fault. What happens if you press "W"?
